#lang scheme

(provide bib)

(define dvanhorn '(a ((href "http://www.ccs.neu.edu/home/dvanhorn/")) "David Van Horn"))
(define might '(a ((href "http://matt.might.net/")) "Matthew Might"))
(define mairson '(a ((href "http://www.cs.brandeis.edu/~mairson/")) "Harry G. Mairson")) 
(define yannis '(a ((href "http://www.cs.umass.edu/~yannis/")) "Yannis Smaragdakis"))
(define matthias '(a ((href "http://www.ccs.neu.edu/home/matthias/")) "Matthias Felleisen"))
(define stchang '(a ((href "http://www.ccs.neu.edu/home/stchang/")) "Stephen Chang"))

(define tfp '(a ((href "http://www-fp.cs.st-andrews.ac.uk/tifp/")) "Symposium on Trends in Functional Programming"))
(define sfp '(a ((href "http://www.schemeworkshop.org/")) "Scheme and Functional Programming Workshop"))
(define sas08 '(a ((href "http://users.dsic.upv.es/~sas2008/")) "Static Analysis Symposium"))

(define bib
  `((publication (authors ,might ,dvanhorn)
                 (title "A Family of Abstract Interpretations for Static Analysis of Concurrent Higher-Order Programs")
                 (date ((month "September") (year 2011)))
                 (download ((format "PDF") (link "http://www.ccs.neu.edu/home/dvanhorn/pubs/might-vanhorn-sas11.pdf")))
                 (published "The 18th International Static Analysis Symposium"))
    (publication (authors ,dvanhorn ,might)
                 (title "Abstracting Abstract Machines")
                 (date ((month "September") (year 2010)))
                 (download ((format "PDF") (link "http://www.ccs.neu.edu/home/dvanhorn/pubs/vanhorn-might-icfp10.pdf")))
                 (published "ICFP"))
    (publication (authors "Christopher Earl" ,might ,dvanhorn)
		 (title "Pushdown Control-Flow Analysis of Higher-Order Programs")
		 (date ((month "August") (year 2010)))
                 (download ((format "PDF") (link "http://www.ccs.neu.edu/home/dvanhorn/pubs/earl-might-vanhorn-sfp10.pdf")))
		 (published ,sfp))
    (publication (authors ,might ,yannis ,dvanhorn)
		 (title "Resolving and Exploiting the k-CFA Paradox")
		 (date ((month "June") (year 2010)))
		 (download ((format "PDF") (link "http://www.ccs.neu.edu/home/dvanhorn/pubs/might-smaragdakis-vanhorn-pldi10.pdf")))
		 (published "PLDI"))
    (publication (authors ,stchang ,dvanhorn ,matthias)
		 (title "Evaluating Call By Need on the Control Stack")
		 (date ((month "May") (year 2010)))
		 (published ,tfp))
    (publication (authors ,dvanhorn ,mairson)
		 (title "Deciding kCFA is complete for EXPTIME")
		 (date ((month "September") (year 2008)))
		 (published "ICFP")
		 (download ((format "PDF") (link "http://www.ccs.neu.edu/home/dvanhorn/pubs/vanhorn-mairson-icfp08.pdf")))
		 (download ((format "ACM") (link "http://doi.acm.org/10.1145/1411204.1411243"))))
    (publication (authors ,dvanhorn)
		 (title "The Complexity of Flow Analysis in Higher-Order Languages")
		 (date ((month "August") (year 2009)))
		 (published "PhD dissertation, Brandeis University")
		 (download ((format "PDF") (link "http://www.ccs.neu.edu/home/dvanhorn/pubs/vanhorn-dissertation.pdf"))))
    (publication (authors ,dvanhorn ,mairson)
		 (title "Flow Analysis, Linearity, and PTIME")
		 (date ((month "July") (year 2008)))
		 (published ,sas08)
		 (download ((format "PDF") (link "http://www.ccs.neu.edu/home/dvanhorn/pubs/vanhorn-mairson-sas08.pdf")))
		 (download ((format "Springer") (link "http://dx.doi.org/10.1007/978-3-540-69166-2_17"))))
    (publication (authors ,dvanhorn ,mairson)
		 (title "Relating Complexity and Precision in Control Flow Analysis")
		 (date ((month "October") (year 2007)))
		 (published "ICFP")
		 (download ((format "PDF") (link "http://www.ccs.neu.edu/home/dvanhorn/pubs/vanhorn-mairson-icfp07.pdf")))
		 (download ((format "ACM") (link "http://doi.acm.org/10.1145/1291151.1291166"))))

    ))
